### ISSUE TITLE
Automated tests via github actions for repositories generated from this template

### ISSUE THREAD

**Issue by famosab** [MetabolicAtlas/standard-GEM#36]
### Description of the issue:
Github actions allows running various jobs in the background when working with a repository. So far this template only offers structure but no automated testing.

#### Expected feature/value/output:
The idea would be to make use of github actions with a small actions script that f. ex. runs memote every time a changed model file is pushed to the repository and then adds the memote report to the repository so that the user can pull the updated report and learn something new about their model.

#### Current feature/value/output:
Not available.

#### Proposed code:
Basically something along the lines of
```yaml
    - name: Install dependencies MEMOTE
      run: python -m pip install memote

    - name: Create memote report 
      run: |
        memote report --filename "GEM_status.html" model/<model_name>.xml 
```

**I hereby confirm that I have:**
- [X] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already
- [X] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue
